using System;
using Ssalddel.Unity.PotatoJourney;
using UnityEngine;
using UnityEngine.UI;

namespace Ssalddel.Unity.Experiments.CityFarmWorldIntegration
{
    public static class PotatoHubReceivingActionCodes{public const string Reset="Reset";public const string ReviewReceiving="ReviewReceiving";public const string Confirm="Confirm";public const string ApplyTick="ApplyTick";public const string ReviewInspection="ReviewInspection";public const string FinishInspection="FinishInspection";public const string GoldenPath="GoldenPath";}
    [DefaultExecutionOrder(400)]public sealed class PotatoHubReceivingLifecyclePresenter:MonoBehaviour
    {
        [SerializeField]private PotatoCargoJourneyLifecyclePresenter journey=null!;[SerializeField]private GameObject receivedMarker=null!;[SerializeField]private GameObject acceptedMarker=null!;[SerializeField]private GameObject rejectedMarker=null!;[SerializeField]private Text stateText=null!;[SerializeField]private Text cargoText=null!;[SerializeField]private Text inspectionText=null!;[SerializeField]private Text lineageText=null!;[SerializeField]private Text actionText=null!;[SerializeField]private Text limitationText=null!;[SerializeField]private bool autoRunGoldenPathOnStart;
        private readonly PotatoHubReceivingSimulationValidator validator=new();private PotatoHubReceivingSimulationEngine engine=null!;private PotatoHubReceivingProjector projector=null!;private PotatoHubReceivingSimulationSnapshot snapshot=null!;private PotatoHubReceivingPreview? preview;private PotatoHubReceivingCommand? command;private PotatoHubReceivingPresentationModel model=null!;
        public PotatoHubReceivingSimulationSnapshot CurrentSnapshot=>snapshot;public PotatoHubReceivingPresentationModel CurrentModel=>model;public PotatoHubReceivingPreview? CurrentPreview=>preview;public PotatoHubReceivingCommand? CurrentCommand=>command;
        public bool ValidateWiring()=>journey!=null&&receivedMarker!=null&&acceptedMarker!=null&&rejectedMarker!=null&&stateText!=null&&cargoText!=null&&inspectionText!=null&&lineageText!=null&&actionText!=null&&limitationText!=null;
        public void Configure(PotatoCargoJourneyLifecyclePresenter j,GameObject received,GameObject accepted,GameObject rejected,Text state,Text cargo,Text inspection,Text lineage,Text action,Text limitation,bool golden){journey=j;receivedMarker=received;acceptedMarker=accepted;rejectedMarker=rejected;stateText=state;cargoText=cargo;inspectionText=inspection;lineageText=lineage;actionText=action;limitationText=limitation;autoRunGoldenPathOnStart=golden;Ensure();ResetLifecycle();}
        private void Start(){Ensure();if(snapshot==null)ResetLifecycle();if(autoRunGoldenPathOnStart)RunGoldenPath();}
        public void ExecuteAction(string code){switch(code){case PotatoHubReceivingActionCodes.Reset:ResetLifecycle();break;case PotatoHubReceivingActionCodes.ReviewReceiving:ReviewReceiving();break;case PotatoHubReceivingActionCodes.Confirm:ConfirmPreview();break;case PotatoHubReceivingActionCodes.ApplyTick:ApplyTick();break;case PotatoHubReceivingActionCodes.ReviewInspection:ReviewInspection();break;case PotatoHubReceivingActionCodes.FinishInspection:FinishInspection();break;case PotatoHubReceivingActionCodes.GoldenPath:RunGoldenPath();break;default:throw new InvalidOperationException("PotatoHubReceivingActionUnknown:"+code);}}
        public void ResetLifecycle(){Ensure();journey.RunGoldenPath();snapshot=PotatoHubReceivingSimulationFixture.Create(journey.CurrentSnapshot);preview=null;command=null;Apply();}
        public void ReviewReceiving(){preview=engine.PreviewReceiving(snapshot);command=null;Apply();}public void ReviewInspection(){preview=engine.PreviewInspection(snapshot);command=null;Apply();}
        public void ConfirmPreview(){if(preview==null)throw new InvalidOperationException("PotatoHubReceivingPreviewMissing");command=engine.Confirm(snapshot,preview);Apply();}
        public void ApplyTick(){if(command==null)throw new InvalidOperationException("PotatoHubReceivingCommandMissing");snapshot=engine.Tick(snapshot,command);preview=null;command=null;Apply();}
        public void FinishInspection(){if(snapshot.StateCode==PotatoHubReceivingStateCodes.ArrivedAtHub){ReviewReceiving();ConfirmPreview();ApplyTick();}if(snapshot.StateCode==PotatoHubReceivingStateCodes.Inspection){ReviewInspection();ConfirmPreview();ApplyTick();}}
        public void RunGoldenPath(){ResetLifecycle();FinishInspection();}
        private void Ensure(){if(engine!=null)return;engine=new PotatoHubReceivingSimulationEngine(validator);projector=new PotatoHubReceivingProjector(validator);}
        private void Apply(){model=projector.Project(snapshot);stateText.text="STATE  "+model.StateCode+"   ·   DATA REV "+snapshot.DataRevision;cargoText.text="CARGO  "+model.CargoText;inspectionText.text="INSPECTION  "+model.InspectionText;lineageText.text="LINEAGE  "+snapshot.HarvestLotStableId+"\n→ "+snapshot.PackageLotStableId+" → "+snapshot.Cargo.StableId;actionText.text=command!=null?"CONFIRMED  "+command.CommandCode+" · APPLY TICK":preview!=null?"REVIEW  "+preview.CommandCode+" · CONFIRM REQUIRED":snapshot.StateCode==PotatoHubReceivingStateCodes.ArrivedAtHub?"ARRIVED · REVIEW RECEIVING":snapshot.StateCode==PotatoHubReceivingStateCodes.Inspection?"INSPECTION · REVIEW DECISION":"ACCEPTED 288kg · REJECTED 12kg · NO INVENTORY CREATED";limitationText.text="LIMIT  "+model.LimitationText;receivedMarker.SetActive(true);acceptedMarker.SetActive(snapshot.StateCode==PotatoHubReceivingStateCodes.Accepted);rejectedMarker.SetActive(snapshot.InspectionResult?.RejectedQuantityKg>0);}
    }
}
